# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlops-cd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mlopscd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ba8cd04005f84086a67657430eff51ce }}
        password: ${{ secrets.AzureAppService_ContainerPassword_104d15190c254f6d8ba547b6e44a7099 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mlopscd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ba8cd04005f84086a67657430eff51ce }}/mlops-cd:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlops-cd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d3979c9eb9964500abfc1bb7269fe4a1 }}
        images: 'mlopscd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ba8cd04005f84086a67657430eff51ce }}/mlops-cd:${{ github.sha }}'